name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
      - run: sudo apt-get update
        shell: bash
      - run: sudo apt-get install -y pkg-config build-essential libudev-dev
        shell: bash
      - run: echo "ANCHOR_VERSION=0.31.1" >> $GITHUB_ENV
        shell: bash
      - run: echo "ANCHOR_SHA=98396c0aeffb4745ab08fb9f45e0d31ad0bd1402" >> $GITHUB_ENV
        shell: bash
      - run: git submodule update --init --recursive --depth 1
        shell: bash
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.82.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: rust-components-${{ runner.os }}-${{ hashFiles('**/rust-toolchain', '**/rust-toolchain.toml') }}
      - run: rustup component add rustfmt
        shell: bash
      - run: rustup component add clippy
        shell: bash
